package poo2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author Diego Itacolomy
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        this.setLocationRelativeTo(null); 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btn_sair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Jmenu = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu_EquipNovo = new javax.swing.JMenuItem();
        jMenu_EquipAtt = new javax.swing.JMenuItem();
        jMenu_EquipExcluir = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu_SoftNovo = new javax.swing.JMenuItem();
        jMenu_SoftAtt = new javax.swing.JMenuItem();
        jMenu_SoftExcluir = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu_ColabNovo = new javax.swing.JMenuItem();
        jMenu_ColabAtt = new javax.swing.JMenuItem();
        jMenu_ColabExcluir = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu_DepartNovo = new javax.swing.JMenuItem();
        jMenu_DepartAtt = new javax.swing.JMenuItem();
        jMenu_DepartExcluir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenuItem2.setText("jMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        btn_sair.setText("Sair");
        btn_sair.setToolTipText("");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(btn_sair)
                .addContainerGap())
        );

        Jmenu.setText("Cadastro");

        jMenu3.setText("Equipamento");

        jMenu_EquipNovo.setText("Novo");
        jMenu_EquipNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_EquipNovoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenu_EquipNovo);

        jMenu_EquipAtt.setText("Atualizar");
        jMenu_EquipAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_EquipAttActionPerformed(evt);
            }
        });
        jMenu3.add(jMenu_EquipAtt);

        jMenu_EquipExcluir.setText("Excluir");
        jMenu_EquipExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_EquipExcluirActionPerformed(evt);
            }
        });
        jMenu3.add(jMenu_EquipExcluir);

        Jmenu.add(jMenu3);

        jMenu4.setText("Software");

        jMenu_SoftNovo.setText("Novo");
        jMenu4.add(jMenu_SoftNovo);

        jMenu_SoftAtt.setText("Atualizar");
        jMenu4.add(jMenu_SoftAtt);

        jMenu_SoftExcluir.setText("Excluir");
        jMenu4.add(jMenu_SoftExcluir);

        Jmenu.add(jMenu4);

        jMenu7.setText("Colaborador");

        jMenu_ColabNovo.setText("Novo");
        jMenu_ColabNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_ColabNovoActionPerformed(evt);
            }
        });
        jMenu7.add(jMenu_ColabNovo);

        jMenu_ColabAtt.setText("Alterar");
        jMenu7.add(jMenu_ColabAtt);

        jMenu_ColabExcluir.setText("Excluir");
        jMenu_ColabExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_ColabExcluirActionPerformed(evt);
            }
        });
        jMenu7.add(jMenu_ColabExcluir);

        Jmenu.add(jMenu7);

        jMenu8.setText("Departamento");

        jMenu_DepartNovo.setText("Novo");
        jMenu8.add(jMenu_DepartNovo);

        jMenu_DepartAtt.setText("Alterar");
        jMenu_DepartAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_DepartAttActionPerformed(evt);
            }
        });
        jMenu8.add(jMenu_DepartAtt);

        jMenu_DepartExcluir.setText("Excluir");
        jMenu8.add(jMenu_DepartExcluir);

        Jmenu.add(jMenu8);

        jMenuBar1.add(Jmenu);

        jMenu2.setText("Inventario");

        jMenu5.setText("Equipamento");
        jMenu2.add(jMenu5);

        jMenu6.setText("Software");
        jMenu2.add(jMenu6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_ColabExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_ColabExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_ColabExcluirActionPerformed

    private void jMenu_DepartAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_DepartAttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_DepartAttActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_sairActionPerformed

    private void jMenu_EquipNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_EquipNovoActionPerformed
        
        TelaEquipamentoCadastro Cad = new TelaEquipamentoCadastro();
        Cad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu_EquipNovoActionPerformed

    private void jMenu_EquipAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_EquipAttActionPerformed
        TelaEquipamentoAtualizacao Att = new TelaEquipamentoAtualizacao();
        Att.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu_EquipAttActionPerformed

    private void jMenu_EquipExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_EquipExcluirActionPerformed
        TelaEquipamentoAtualizacao Att = new TelaEquipamentoAtualizacao();
        Att.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu_EquipExcluirActionPerformed

    private void jMenu_ColabNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_ColabNovoActionPerformed
        TelaColaboradorCadastro Tcc = new TelaColaboradorCadastro();
        Tcc.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jMenu_ColabNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Jmenu;
    private javax.swing.JButton btn_sair;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenu_ColabAtt;
    private javax.swing.JMenuItem jMenu_ColabExcluir;
    private javax.swing.JMenuItem jMenu_ColabNovo;
    private javax.swing.JMenuItem jMenu_DepartAtt;
    private javax.swing.JMenuItem jMenu_DepartExcluir;
    private javax.swing.JMenuItem jMenu_DepartNovo;
    private javax.swing.JMenuItem jMenu_EquipAtt;
    private javax.swing.JMenuItem jMenu_EquipExcluir;
    private javax.swing.JMenuItem jMenu_EquipNovo;
    private javax.swing.JMenuItem jMenu_SoftAtt;
    private javax.swing.JMenuItem jMenu_SoftExcluir;
    private javax.swing.JMenuItem jMenu_SoftNovo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
